Replace
it-top-lipetsk/ReplacWords pull request #1
Opened 2022-03-04 15:46 UTC by word-guru

2022-03-04 15:46 UTC, word-guru commented
![](https://github.trello.services/images/mini-trello-icon.png) [Замена слов](https://trello.com/c/VVuEH0mv/4-%D0%B7%D0%B0%D0%BC%D0%B5%D0%BD%D0%B0-%D1%81%D0%BB%D0%BE%D0%B2)

2022-03-04 15:56 UTC, AlekseiTeterin approved these changes

2022-03-04 15:56 UTC, AleksCoder88 commented on ReplacWords.Lib/Replace.cs
> +        public override string ToString() => $"{Word}";
for delete

2022-03-04 16:11 UTC, anst-foto requested changes
Переработать для работы не с отдельным словом, а со строкой.

2022-03-04 16:11 UTC, anst-foto commented on ReplacWords.Lib/Replace.cs
> +﻿using ReplacWords.Lib;
Необходимость данного подключения библиотеки?

2022-03-04 16:11 UTC, anst-foto commented on ReplacWords.Lib/Replace.cs
> +            if (Word is not null && Word != "")
```suggestion
            if (string.IsNullOrEmpty(Word) || string.IsNullOrWhitespace(Word)) return;
```

2022-03-04 16:11 UTC, anst-foto commented on ReplacWords.Lib/Replace.cs
> +                }
Проработать возможность использования метода `Replace` в `string` - https://docs.microsoft.com/ru-ru/dotnet/api/system.string.replace?view=net-6.0

2022-03-11 15:51 UTC, AlekseiTeterin approved these changes
Согласен с изменениями

2022-03-11 15:59 UTC, anst-foto approved these changes
Принимается

2022-03-11 15:59 UTC, anst-foto commented on ReplacWords.Lib/Replace.cs
> +                _word.Add(l, temp);
Желательно вынести в отдельный метод

2022-03-11 15:59 UTC, anst-foto commented on ReplacWords.Lib/Replace.cs
> +                _word.Add(l, temp);
Желательно вынести в отдельный метод

2022-03-11 16:02 UTC, merged