Searc words
it-top-lipetsk/ReplacWords pull request #2
Opened 2022-03-04 17:50 UTC by AlekseiTeterin

2022-03-04 17:51 UTC, AlekseiTeterin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Поиск слов в файле](https://trello.com/c/xwzHan1C/3-%D0%BF%D0%BE%D0%B8%D1%81%D0%BA-%D1%81%D0%BB%D0%BE%D0%B2-%D0%B2-%D1%84%D0%B0%D0%B9%D0%BB%D0%B5)

2022-03-04 17:59 UTC, ArhiMurder approved these changes
Всё хорошо было сделано. Ошибок не замечено

2022-03-04 18:12 UTC, anst-foto requested changes
Учесть комментарии к тексту программы.
Постараться код поска искомых слов выделить в отдельную функцию - большая вложенность

2022-03-04 18:12 UTC, anst-foto commented on ReplacWords.Lib/Search.cs
> +        string[] forbiddenWords = new string[size];
- Инициализация производится в конструкторе.
- Нет модификаторов доступности

2022-03-04 18:12 UTC, anst-foto commented on ReplacWords.Lib/Search.cs
> +             Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
Путь не определяется в классе, а передаётся через конструктор.

2022-03-04 18:12 UTC, anst-foto commented on ReplacWords.Lib/Search.cs
> +            var Files = Directory.EnumerateFiles(docsPath, "*.txt", SearchOption.AllDirectories);
Проверять можно не только файлы с расширением `*.txt`

2022-03-04 18:12 UTC, anst-foto commented on ReplacWords.Lib/Search.cs
> +                while ((line = f.ReadLine()) != null)
Не обязательно считывать построчно, можно сразу весь файл считать, и потом искать

2022-03-11 16:30 UTC, KirillLagutin approved these changes, later dismissed

2022-03-11 16:36 UTC, anst-foto requested changes
Переработать класс с учётом комментариев

2022-03-11 16:36 UTC, anst-foto commented on ReplacWords.Lib/Search.cs
> +        //internal static string controlFolder = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments) + "/ForbiddenFiles";
Комментарии

2022-03-11 16:36 UTC, anst-foto commented on ReplacWords.Lib/Search.cs
> +                //Console.WriteLine($"Текст из файла: {textFromFile}");
```suggestion
var file = File.ReadToEnd(); // Примерный код для сокращения
```
```

2022-03-11 16:46 UTC, anst-foto reviewed
Добавить асинхронные методы

2022-03-13 18:26 UTC, KirillLagutin requested changes

2022-03-13 18:26 UTC, KirillLagutin commented on ReplacWords.Lib/Search.cs
> +        public string controlFolder;
```suggestion
        public const int size = 10;
        public string[] forbiddenWords;
        public string docsPath;
        public string controlFolder;
        public static string[] ArrBannedWordFile;
```

2022-03-13 18:26 UTC, KirillLagutin commented on ReplacWords.Lib/Search.cs
> +        public string controlFolder;
Просьба создать публичный массив файлов, и в него добавлять файлы, если в них замечены запрещённые слова.

2022-03-13 18:26 UTC, KirillLagutin commented on ReplacWords.Lib/Search.cs
> +        }
Просьба создать метод для добавления элементов в массив.
```suggestion
public static string AddElement(ref string[] array, string element)
{
  string temp[] = new array[array.Length+1];
  temp[array.Length] = element;
  for(int i=0; i<array.Length; i++)
  tamp[i] = array[i];
  array = temp;
}
        }   
```

2022-03-13 18:26 UTC, KirillLagutin commented on ReplacWords.Lib/Search.cs
> +                    File.Copy(currentFile, Path.Combine(controlFolder, fileName));
Просьба добавлять fileName в массив ArrBannedWordFile.
```suggestion
                    string fileName = currentFile.Substring(docsPath.Length + 1);
                    File.Copy(currentFile, Path.Combine(controlFolder, fileName));
                    AddElement(ref ArrBannedWordFile, fileName);
```

2022-03-15 15:45 UTC, anst-foto approved these changes
Принимается

2022-03-15 15:45 UTC, merged