Add class Report
it-top-lipetsk/ReplacWords pull request #3
Opened 2022-03-09 22:21 UTC by KirillLagutin

2022-03-09 22:22 UTC, KirillLagutin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Создание отчёта](https://trello.com/c/wnNvKxu4/5-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%BE%D1%82%D1%87%D1%91%D1%82%D0%B0)

2022-03-11 16:16 UTC, word-guru requested changes

2022-03-11 16:16 UTC, word-guru commented on ReplacWords.Lib/Report.cs
> +            string pathForWrite = @"D:\!Desktop\Step\C#\Projects\ReplacWords\file_report.txt";
Передать путь к файлу параметром

2022-03-11 16:16 UTC, word-guru commented on ReplacWords.Lib/Report.cs
> +        }
Заменить на имеющуюся переменную

2022-03-11 16:28 UTC, anst-foto requested changes
Доработать с учётом комментариев

2022-03-11 16:28 UTC, anst-foto commented on ReplacWords.Lib/Report.cs
> +        string[] bannedWordFile = Directory.GetFiles(pathDir, "*.txt");
Искать желательно не только `*.txt` файлы

2022-03-11 16:28 UTC, anst-foto commented on ReplacWords.Lib/Report.cs
> +                    CountAll += CountForbiddenWords(bannedWordFile[i]);
Двойной вызов метода не оптимален. Лучше использовать переменную, в которую запишется результат метода `CountForbiddenWords()`

2022-03-11 16:28 UTC, anst-foto commented on ReplacWords.Lib/Report.cs
> +        }
Лишний метод. Необходимо использовать значение замен из методов в задаче @word-guru

2022-03-11 16:28 UTC, anst-foto commented on ReplacWords.Lib/Report.cs
> +        }
Лишний метод.

2022-03-11 16:28 UTC, anst-foto commented on ReplacWords.Lib/Report.cs
> +                await sw.WriteLineAsync($"Общее колличество найденных файлов: {CountAll}");
```suggestion
                await sw.WriteLineAsync($"Общее количество заменённых слов: {CountAll}");
```

2022-03-12 16:17 UTC, anst-foto requested changes
Не все старые замечания выполнены, плюс появились новые.

2022-03-12 16:17 UTC, anst-foto commented on ReplacWords.Lib/Report.cs
> +using Microsoft.VisualBasic;
```suggestion
```

2022-03-12 16:17 UTC, anst-foto commented on ReplacWords.Lib/Report.cs
>          static string pathDir = "";
Зачем здесь статичная переменная?

2022-03-12 16:17 UTC, anst-foto commented on ReplacWords.Lib/Report.cs
> +        string pathForWrite = @"D:\!Desktop\Step\C#\Projects\ReplacWords\file_report.txt";
Нужно не просто указывать путь, а передавать его из вне.

2022-03-13 18:50 UTC, KirillLagutin commented
Этого кода нет уже, я его переделал с учётом что Алексей добавит в своём коде
массив ArrBannedWordFile и метод AddElement.
Поспешил на проверку отправлять, но код уже был изменён, не знаю почему у Вас старый код показывается,
может из-за того что я ветки не слил...
но вот [правильный код](https://github.com/itstep-lipetsk/ReplacWords/blob/report/ReplacWords.Lib/Report.cs), на проверку отправлю тогда после Алексея.

2022-03-15 17:10 UTC, anst-foto approved these changes
Принимается

2022-03-15 17:10 UTC, anst-foto commented on ReplacWords.Lib/Replace.cs
> +        public static int NumberOfSubstitutions { get; set; }
Откатить изменения

2022-03-15 17:10 UTC, merged